### PR TITLE
Close #33 Fix problem add product in active sale event not discount

### LINKED ISSUE #33: Fix problem add product in active sale event  not having discount

### PR DESCRIPTION
**Pull request by sokmesakhiev**

### CODE REVIEW

File: app/controllers/spree/admin/active_sale_events_controller.rb [hunk 1]
```diff
@@ -26,11 +29,20 @@ def update
...
           params[:active_sale_event][:taxon_ids] = params[:active_sale_event][:taxon_ids].split(',')
         end
+
         super
       end
 
       private
 
+        def create_promotion
+          CreatePromotion.call(active_sale_event: @object)
```
Comment (channainfo) [inline app/controllers/spree/admin/active_sale_events_controller.rb:39]: let's move the logic to ActiveSaleEventCreator/Updater service and remove after_action.

File: app/controllers/spree/admin/sale_products_controller.rb [hunk 2]
```diff
@@ -3,24 +3,22 @@ module Admin
...
-            format.js   { render layout: false }
-          end
-        else
-          invoke_callbacks(:create, :fails)
-          respond_with(@object) do |format|
-            format.html { render action: :new }
-            format.js { render layout: false }
-          end
-        end
+      def create_product_promotion_rule
```
Comment (channainfo) [inline app/controllers/spree/admin/sale_products_controller.rb:9]: let create new services to handle this instead of using controller callback.

**Review by channainfo — CHANGES_REQUESTED** [review]

**Review by channainfo — CHANGES_REQUESTED** [review]

File: app/controllers/spree/admin/active_sale_events_controller.rb [hunk 3]
```diff
@@ -5,14 +5,51 @@ class ActiveSaleEventsController < ResourceController
...
+
       def show
         session[:return_to] ||= request.referer
         redirect_to( :action => :edit )
       end
 
       def destroy
-        @active_sale_event = Spree::ActiveSaleEvent.find(params[:id])
-        @active_sale_event.delete
+        ActiveSaleEventDestroyer.call(active_sale_event: @active_sale_event)
```
[the remark this answers is not in the document]
Comment (sokmesakhiev) [reply app/controllers/spree/admin/active_sale_events_controller.rb:52]: Spree doing destroy for promotion so i believe it should play the same to promotion
