### PR TITLE
Close #47 fix conflict name space active sale

### LINKED ISSUE #47: service name space active_sale conflict with model active_sale

### PR DESCRIPTION
**Pull request by sokmesakhiev**

### CODE REVIEW

File: app/controllers/spree/admin/active_sale_events_controller.rb [hunk 1]
```diff
@@ -7,7 +7,7 @@ class ActiveSaleEventsController < ResourceController
 
       def create
         active_sale_event_params = permitted_resource_params.merge(active_sale_id: @active_sale.id)
-        context = ActiveSale::ActiveSaleEventCreator.call(params: active_sale_event_params)
+        context = ActiveSales::ActiveSaleEventCreator.call(params: active_sale_event_params)
```
Comment (channainfo) [inline app/controllers/spree/admin/active_sale_events_controller.rb]: @sokmesakhiev why do we need to use **ActiveSales** plural as a module?

**Review by channainfo — CHANGES_REQUESTED** [review]

File: app/controllers/spree/admin/active_sale_events_controller.rb (hunk 1 above)
Comment (sokmesakhiev) [reply app/controllers/spree/admin/active_sale_events_controller.rb]: It will conflict with ActiveSale model that one is class and one is module

Comment (sokmesakhiev) [reply app/controllers/spree/admin/active_sale_events_controller.rb]: Maybe it is good to have a namespace as Flash Sale instead of ActiveSale
